### ISSUE TITLE
JavaScript out of memory | Angular compiler

### ISSUE THREAD

**Issue by javierscode** [midudev/hacktoberfest-2022#75]
Hi guys,

I just cloned the repository, installed the dependencies and run the `npm run dev` command and when i try to visit the homesite... node fails with an out of memory after a lot of issues from angular compiler.

| Angular compiler errors  | Out of memory|
| ------------- | ------------- |
| ![image](https://user-images.githubusercontent.com/59363092/193463748-19e6b261-ef1a-461e-9625-faf5e9a0fde8.png)  | ![image](https://user-images.githubusercontent.com/59363092/193464035-1d561723-f642-47e6-977c-67d6005fa839.png)  |

My first thought was... oh I just need to install the react types the console was asking for, but after doing it I'm in the same spot, the node continues failing for the same cause.

| Angular compiler errors  | Out of memory|
| ------------- | ------------- |
| ![image](https://user-images.githubusercontent.com/59363092/193464307-4283dd6c-a057-4e1a-8088-f7f7aad163b0.png)  | ![image](https://user-images.githubusercontent.com/59363092/193464355-35f83d7e-da46-44e2-89f8-8347dc239a2e.png) |

My specs:
 - Windows 11
 - Powershell 7.2.6 or  Bash 4.4.23

**Comment by midudev** [comment]
Hemos eliminado Angular por todos los problemas que estaba dando. Ahora ya funciona correctamente.

**Comment by javierscode** [comment]
Gracias!
