### ISSUE TITLE
Move angular dependencies to devDependencies

### ISSUE THREAD

**Issue by marsidev** [midudev/hacktoberfest-2022#78]
According to [Analog docs](https://analogjs.org/docs/packages/astro-angular/overview), there is some dependencies that are needed to install as `devDependencies` but are installed in this project as [`dependencies`](https://github.com/midudev/hacktoberfest-2022/blob/74fc33fdb5ddb17a69da23f483a5e7ebc3475383/package.json#L17-L45).

![image](https://user-images.githubusercontent.com/56328053/193466800-dcf773d1-2511-4050-a600-35fac99e0359.png)

**Comment by midudev** [comment]
Hemos eliminado la integración con Angular por los problemas que estaba dando. Como está en beta y no es oficial, vamos a no darle soporte. Tampoco nadie la había usado todavía.

**Comment by jrafaaael** [comment]
@midudev también debería ser eliminado del readme, así como solid. En la página de inicio también hay un typo (Keychrone, en lugar de Keychron 🙂)

**Comment by marsidev** [comment]
Actualicé los frameworks del readme en esta [PR](https://github.com/midudev/hacktoberfest-2022/pull/82), pero no el typo de Keychron.
