### ISSUE TITLE
Agregar hacktoberfest o hacktoberfest-accepted a los labels disponibles

### ISSUE THREAD

**Issue by luisfalconmx** [midudev/hacktoberfest-2022#79]
Se necesita agregar las etiquetas mencionadas en el titulo ya que a si lo indica la pagina oficial del [hacktoberfest](https://hacktoberfest.com/participation/)

> Your PR/MRs must be in a repo tagged with the “hacktoberfest” topic, or be labeled “hacktoberfest-accepted.”
> Hacktoberfest is now opt-in for maintainers, so only contribute to projects that indicate they’re looking for Hacktoberfest PR/MRs.

> Once your PR/MR has passed this check, we won’t check this again (unless your PR/MR fails a check before this, such as it being marked as spammy).

**Comment by midudev** [comment]
Es un OR. Nosotros ya tenemos el topic `hacktoberfest` y no es necesario tener esos labels en las PRs si no queremos. :)
