### ISSUE TITLE
add @types/react :pray:

### ISSUE THREAD

**Issue by jrafaaael** [midudev/hacktoberfest-2022#94]

**Comment by marsidev** [comment]
Lo agregué en esta [PR](https://github.com/midudev/hacktoberfest-2022/pull/90)

**Comment by jrafaaael** [comment]
> Lo agregué en esta [PR](https://github.com/midudev/hacktoberfest-2022/pull/90)

quizá tu PR hace muchas cosas. Esperemos que midu le haga merge de igual forma! :smile:
